SIM:
  TRAININGSIM:
    IA_G10:
      BASE: sn_ia_salt2_g10.input
    II_JONES:
      BASE: sn_collection_jones.input
    GLOBAL:
      NGEN_UNIT: 0.3
      RANSEED_REPEAT: 10 12345

  TESTSIM:
    IA_C11:
      BASE: sn_ia_salt2_c11.input
    IBC_TEMPLATES:
      BASE: sn_ibc_templates.input
    II_TEMPLATES:
      BASE: sn_ii_templates.input
    GLOBAL:
      NGEN_UNIT: 0.3
      RANSEED_REPEAT: 5 12345

LCFIT:
  TESTFIT:
    BASE: des.nml

CLASSIFICATION:
  SNIRF-TRAIN-x1cF:
    CLASSIFIER: SnirfClassifier
    MODE: train
    MASK_SIM: TRAINING
    OPTS:
      FEATURES: x1 c FITPROB

  SNIRF-TEST-x1cF:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    MASK_SIM: TESTSIM
    OPTS:
      MODEL: SNIRF-TRAIN-x1cF
      FEATURES: x1 c FITPROB

  SNIRF-TRAIN-WERR:
    CLASSIFIER: SnirfClassifier
    MODE: train
    MASK_SIM: TRAINING
    OPTS:
      FEATURES: x1 c zHD x1ERR cERR PKMJDERR

  SNIRF-TEST-WERR:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    MASK_SIM: TESTSIM
    OPTS:
      MODEL: SNIRF-TRAIN-WERR
      FEATURES: x1 c zHD x1ERR cERR PKMJDERR

  SNIRF-TRAIN-WERR-FITPROB:
    CLASSIFIER: SnirfClassifier
    MODE: train
    MASK_SIM: TRAINING
    OPTS:
      FEATURES: x1 c zHD x1ERR cERR PKMJDERR FITPROB

  SNIRF-TEST-WERR-FITPROB:
    CLASSIFIER: SnirfClassifier
    MODE: predict
    MASK_SIM: TESTSIM
    OPTS:
      MODEL: SNIRF-TRAIN-WERR-FITPROB
      FEATURES: x1 c zHD x1ERR cERR PKMJDERR FITPROB

  FITPROBTEST:
    CLASSIFIER: FitProbClassifier
    MODE: predict
    MASK: TEST

AGGREGATION:
  AGG:
    MASK: TEST
    OPTS:
      INCLUDE_TYPE: True
      PLOT: True
